/**
 * 389. Find the Difference
 *
 * You are given two strings s and t. String t is generated by random shuffling
 * string s and then add one more letter at a random position. Return the letter
 * that was added to t.
 */

#include <catch2/catch_test_macros.hpp>
#include <string>
#include <unordered_map>
#include <vector>

using namespace std;

/**
 * n: length of the input strings
 * Time: O(n)
 * Space: O(1)
 */
class Solution1 {
public:
    char findTheDifference(string s, string t) {
        int num_chars = 1 << (sizeof(char) * 8); // should be 256
        vector<int> s_freq(num_chars, 0), t_freq(num_chars, 0);

        for (char c : s) {
            s_freq[c]++;
        }
        for (char c : t) {
            t_freq[c]++;
        }

        for (int i = 0; i < num_chars; ++i) {
            if (s_freq[i] != t_freq[i]) {
                return i;
            }
        }

        return 0;
    }
};

/**
 * n: length of the input strings
 * Time: O(n)
 * Space: O(1)
 */
class Solution2 {
public:
    char findTheDifference(string s, string t) {
        unordered_map<char, int> s_freq, t_freq;

        for (char c : s) {
            auto it = s_freq.find(c);
            if (it == s_freq.end()) {
                s_freq[c] = 1;
            } else {
                it->second++;
            }
        }
        for (char c : t) {
            auto it = t_freq.find(c);
            if (it == t_freq.end()) {
                t_freq[c] = 1;
            } else {
                it->second++;
            }
        }

        for (auto &[c, times] : t_freq) {
            auto it = s_freq.find(c);
            if (it == s_freq.end() || it->second != times) {
                return c;
            }
        }

        return 0;
    }
};

TEST_CASE("Find the Difference") {
    Solution2 s;

    SECTION("") {
        CHECK(s.findTheDifference("abcd", "abcde") == 'e');
        CHECK(s.findTheDifference("", "y") == 'y');
    }
}
